config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :suggestions
  resources :faqs
  resources :testimonials
  devise_for :users
  resources :members

  get 'about' => "pages#about"
  get 'geeb' => "pages#geeb"
  get 'team' => "pages#team"
  get 'terms' => "pages#terms"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: %i[ show edit update destroy ]

  # GET /suggestions or /suggestions.json
  def index
    @suggestions = Suggestion.all
  end

  # GET /suggestions/1 or /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions or /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: "Suggestion was successfully created." }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1 or /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: "Suggestion was successfully updated." }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1 or /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: "Suggestion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def suggestion_params
      params.require(:suggestion).permit(:title, :message, :link)
    end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= simple_form_for(@suggestion) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :message %>
    <%= f.input :link %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suggestions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.title %></td>
        <td><%= suggestion.message %></td>
        <td><%= suggestion.link %></td>
        <td><%= link_to 'Show', suggestion %></td>
        <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
        <td><%= link_to 'Destroy', suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suggestion', new_suggestion_path %>

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @suggestion.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @suggestion.message %>
</p>

<p>
  <strong>Link:</strong>
  <%= @suggestion.link %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>